// The agents a phase-per-agent workflow attaches, and the run one phase dispatched.
//
// One of the workflow fixture's four data modules; `workflow-fixture-ids.ts` carries
// the framing all four share. This is the table that is NOT declared by
// `bridge/workflow-projection.ts`: an attached agent is a session fact carried on a
// `packages/contracts` beat, so it sits beside neither the definitions nor the runs
// even though a workflow's phases are what dispatch to it.

const AGENT_PLANNER = "019b7a10-0280-7a6e-8100-d1a4c1150001";
const AGENT_BUILDER = "019b7a10-0280-7a6e-8100-d1a4c1150002";

/**
 * One agent a workflow's phases dispatch to, as both the beat and the reply carry it.
 *
 * Named rather than inferred from an `as const` literal because the table is exported
 * and `isolatedDeclarations` is repo-wide: an exported value needs a type a reader and
 * a declaration emitter can both see without reading the initializer.
 */
interface WorkflowScenarioAgent {
  readonly agentId: string;
  /**
   * The daemon's opaque row id for the attach event this row produces.
   *
   * Carried on the table rather than composed at the beat, on the flagship's
   * precedent: the beats are generated by a `map`, and a composed id would be the one
   * member of the envelope no daemon minted.
   */
  readonly eventId: string;
  readonly name: string;
  readonly driverName: string;
  readonly modelId: string;
  /** The tick the attach beat is due at, measured from scenario start. */
  readonly attachedAtMs: number;
  readonly attachedAtIso: string;
}

/**
 * The two agents a phase-per-agent workflow attaches, as the `agents` projection
 * carries them.
 *
 * One table rather than a literal per beat and a second per reply, on the flagship's
 * precedent: the `agent.attached` payload is the replay-complete record `Spec-006
 * §Channel and Agent Lifecycle (session_lifecycle)` makes it, so the projection
 * rebuilds from it alone, and two hand-written copies of one agent would drift in
 * exactly the direction nothing catches. The drivers are deliberately mixed so the
 * parked story can show one phase waiting on a spent account while the other runs.
 */
export const WORKFLOWS_SCENARIO_AGENTS: readonly WorkflowScenarioAgent[] = [
  {
    agentId: AGENT_PLANNER,
    eventId: "019b7a10-0280-7ea1-8110-e5e0d1150002",
    name: "Planner",
    driverName: "claude",
    modelId: "claude-opus-5[1m]",
    attachedAtMs: 80,
    attachedAtIso: "2026-01-01T07:00:00.080Z",
  },
  {
    agentId: AGENT_BUILDER,
    eventId: "019b7a10-0280-7ea1-8110-e5e0d1150003",
    name: "Builder",
    driverName: "codex",
    modelId: "gpt-5.6-sol",
    attachedAtMs: 160,
    attachedAtIso: "2026-01-01T07:00:00.160Z",
  },
];

/** The run one `single-agent` phase dispatched, and the only run on the event stream. */
export const WORKFLOWS_PHASE_AGENT_RUN_ID: string = "019b7a10-0280-740e-8100-d1a4c1150011";

/** The agent that phase dispatched to. Named so the beat and the table agree. */
export const WORKFLOWS_PHASE_AGENT_ID: string = AGENT_BUILDER;
